### ISSUE TITLE
ERROR: Unsupported extension

### ISSUE THREAD

**Issue by LaDuelo** [RCatersels/TemplaterForMendix#1]
When running the example project in Mendix 7.23.6 I get an error saying "Unsupported filetype"
I've tried the example .docx document as well as my own but I always get the same error. I've attached the stacktrace for you to take a look.
[Stack trace.txt](https://github.com/RCatersels/TemplaterForMendix/files/3426792/Stack.trace.txt)

**Comment by RCatersels** [comment]
May I ask what kind of a file you tried to upload? The supported file types are:
    DOCM("Macro-Enabled Office Open XML document (Word)"),
    DOCX("Office Open XML document (Word)"),
    XLSM("Macro-Enabled Office Open XML spreadsheet (Excel)"),
    XLSX("Office Open XML spreadsheet (Excel)"),
    CSV("Comma separated values document"),
    TXT("Text file (native encoding)"),
    UTF8("Text file (UTF-8 encoding)");

Regards,
Ronald

**Comment by LaDuelo** [comment]
I've tried a .docx file (both saved as Microsoft variant and Strict Open XML Document). Additionally, I've also tried the original template document found in the project:
[WordTemplate_Example1.docx](https://github.com/RCatersels/TemplaterForMendix/files/3426878/WordTemplate_Example1.docx)

**Comment by RCatersels** [comment]
Indeed when converting to 7.23.6 a Java error is generated. I will try to debug tonight what might be the cause of this. I have double checked the project without conversion (so in 7.18.1) and there it works as it should. So if you only want to check out how all works I advise not yet to update to 7.23.6.  I will give an update when I have found the cause.
Regards,

Ronald

**Comment by RCatersels** [comment]
Found the bug. Published a new version to the appstore. You can also download new version directly from here.
Regards,
Ronald
